export const refs = {
  openTeamModal: document.querySelector('[data-team-modal-open]'),
  closeTeamModal: document.querySelector('[data-team-modal-close]'),
  teamModal: document.querySelector('[data-team-modal]'),
  // teamBackdrop: document.querySelector('.team-modal-mask'),
  teamBackdrop: document.querySelector('.js-movie-modal-mask'), // Заміна бекдропу
  body: document.querySelector('body'),
  cardHolderLibrary: document.querySelector('.card-holder'),
  footerLink: document.querySelector('.footer__link'),
  stickyHeaderMyLibrary: document.querySelector('.js-my-library-header__sticky'),
  watchedBtn: document.querySelector('.js-watched'),
  queuedBtn: document.querySelector('.js-queue'),
  //кнопки для свернутого хедера
  watchedBtnSticky: document.querySelector('.js-watched__sticky'),
  queuedBtnSticky: document.querySelector('.js-queue__sticky'),
  movieModal: document.querySelector('.js-movie-modal'),
  pagination: document.querySelector('.pagination__container'),
  searchForm: document.querySelector('.home-header__form'),
  stickyHeaderForm: document.querySelector('.home-header__form__sticky'),
  cardHolder: document.querySelector('.card-holder'),
  // conteiner: document.querySelector('.card-container.container'),
  stickyHeader: document.querySelector('.js-home-header__sticky'),
  stickyHeaderForm: document.querySelector('.home-header__form__sticky'),
  footerLink: document.querySelector('.footer__link'),
  ruBackdrop: document.querySelector("[data-backdrop]"),
  backdrop: document.querySelector('.js-movie-modal-mask'),
  img:document.querySelector('.empty__page'),
  text: document.querySelector('.empty__page-text'),
  filmModal :document.querySelector('.js-movie-modal'),
  filmModalMask :document.querySelector('.js-movie-modal-mask'),
  trailerBackdrop: document.querySelector('.js-movie-modal-mask'),
  pagination: document.querySelector('.pagination__container'),
};
